services:
  app:
    build: .
    container_name: fitness-app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      POSTGRE_SQL: postgresql://postgres:postgres@db:5432/fitness_app
      PORT: 8000
      NODE_ENV: production
    ports:
      - '8000:8000'
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    container_name: fitness-app-db
    environment:
      POSTGRES_DB: fitness_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d fitness_app']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data:
